deals/config/routes.rb
Deals::Application.routes.draw do
  
  match "conversion/uploadFile", :via => 'post'
  resources :conversion

  resources :purchaser_deals

  resources :deals

  resources :merchants

  resources :purchasers

end

deals/app/models/purchaser.rb
class Purchaser < ActiveRecord::Base
  has_many :purchaserDeals
end

deals/app/controllers/purchasers_controller.rb
class PurchasersController < ApplicationController
  # GET /purchasers
  # GET /purchasers.json
  def index
    @purchasers = Purchaser.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @purchasers }
    end
  end

  # GET /purchasers/1
  # GET /purchasers/1.json
  def show
    @purchaser = Purchaser.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @purchaser }
    end
  end

  # GET /purchasers/new
  # GET /purchasers/new.json
  def new
    @purchaser = Purchaser.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @purchaser }
    end
  end

  # GET /purchasers/1/edit
  def edit
    @purchaser = Purchaser.find(params[:id])
  end

  # POST /purchasers
  # POST /purchasers.json
  def create
    @purchaser = Purchaser.new(params[:purchaser])

    respond_to do |format|
      if @purchaser.save
        format.html { redirect_to @purchaser, notice: 'Purchaser was successfully created.' }
        format.json { render json: @purchaser, status: :created, location: @purchaser }
      else
        format.html { render action: "new" }
        format.json { render json: @purchaser.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /purchasers/1
  # PUT /purchasers/1.json
  def update
    @purchaser = Purchaser.find(params[:id])

    respond_to do |format|
      if @purchaser.update_attributes(params[:purchaser])
        format.html { redirect_to @purchaser, notice: 'Purchaser was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @purchaser.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purchasers/1
  # DELETE /purchasers/1.json
  def destroy
    @purchaser = Purchaser.find(params[:id])
    @purchaser.destroy

    respond_to do |format|
      format.html { redirect_to purchasers_url }
      format.json { head :ok }
    end
  end
end

deals/app/helpers/purchasers_helper.rb
module PurchasersHelper
end

deals/app/views/purchasers/_form.html.erb
<%= form_for(@purchaser) do |f| %>
  <% if @purchaser.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@purchaser.errors.count, "error") %> prohibited this purchaser from being saved:</h2>

      <ul>
      <% @purchaser.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

deals/app/views/purchasers/edit.html.erb
<h1>Editing purchaser</h1>

<%= render 'form' %>

<%= link_to 'Show', @purchaser %> |
<%= link_to 'Back', purchasers_path %>

deals/app/views/purchasers/index.html.erb
<h1>Listing purchasers</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @purchasers.each do |purchaser| %>
  <tr>
    <td><%= purchaser.name %></td>
    <td><%= link_to 'Show', purchaser %></td>
    <td><%= link_to 'Edit', edit_purchaser_path(purchaser) %></td>
    <td><%= link_to 'Destroy', purchaser, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Purchaser', new_purchaser_path %>

deals/app/views/purchasers/new.html.erb
<h1>New purchaser</h1>

<%= render 'form' %>

<%= link_to 'Back', purchasers_path %>

deals/app/views/purchasers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @purchaser.name %>
</p>


<%= link_to 'Edit', edit_purchaser_path(@purchaser) %> |
<%= link_to 'Back', purchasers_path %>