deals/config/routes.rb
Deals::Application.routes.draw do
  
  match "conversion/uploadFile", :via => 'post'
  resources :conversion

  resources :purchaser_deals

  resources :deals

  resources :merchants

  resources :purchasers

end

deals/app/models/purchaser_deal.rb
class PurchaserDeal < ActiveRecord::Base
  belongs_to :purchaser
  belongs_to :deal
end

deals/app/controllers/purchaser_deals_controller.rb
class PurchaserDealsController < ApplicationController
  # GET /purchaser_deals
  # GET /purchaser_deals.json
  def index
    @purchaser_deals = PurchaserDeal.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @purchaser_deals }
    end
  end

  # GET /purchaser_deals/1
  # GET /purchaser_deals/1.json
  def show
    @purchaser_deal = PurchaserDeal.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @purchaser_deal }
    end
  end

  # GET /purchaser_deals/new
  # GET /purchaser_deals/new.json
  def new
    @purchaser_deal = PurchaserDeal.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @purchaser_deal }
    end
  end

  # GET /purchaser_deals/1/edit
  def edit
    @purchaser_deal = PurchaserDeal.find(params[:id])
  end

  # POST /purchaser_deals
  # POST /purchaser_deals.json
  def create
    @purchaser_deal = PurchaserDeal.new(params[:purchaser_deal])

    respond_to do |format|
      if @purchaser_deal.save
        format.html { redirect_to @purchaser_deal, notice: 'Purchaser deal was successfully created.' }
        format.json { render json: @purchaser_deal, status: :created, location: @purchaser_deal }
      else
        format.html { render action: "new" }
        format.json { render json: @purchaser_deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /purchaser_deals/1
  # PUT /purchaser_deals/1.json
  def update
    @purchaser_deal = PurchaserDeal.find(params[:id])

    respond_to do |format|
      if @purchaser_deal.update_attributes(params[:purchaser_deal])
        format.html { redirect_to @purchaser_deal, notice: 'Purchaser deal was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @purchaser_deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purchaser_deals/1
  # DELETE /purchaser_deals/1.json
  def destroy
    @purchaser_deal = PurchaserDeal.find(params[:id])
    @purchaser_deal.destroy

    respond_to do |format|
      format.html { redirect_to purchaser_deals_url }
      format.json { head :ok }
    end
  end
end

deals/app/helpers/purchaser_deals_helper.rb
module PurchaserDealsHelper
end

deals/app/views/purchaser_deals/_form.html.erb
<%= form_for(@purchaser_deal) do |f| %>
  <% if @purchaser_deal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@purchaser_deal.errors.count, "error") %> prohibited this purchaser_deal from being saved:</h2>

      <ul>
      <% @purchaser_deal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :purchaser %><br />
    <%= f.text_field :purchaser %>
  </div>
  <div class="field">
    <%= f.label :deal %><br />
    <%= f.text_field :deal %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

deals/app/views/purchaser_deals/edit.html.erb
<h1>Editing purchaser_deal</h1>

<%= render 'form' %>

<%= link_to 'Show', @purchaser_deal %> |
<%= link_to 'Back', purchaser_deals_path %>

deals/app/views/purchaser_deals/index.html.erb
<h1>Listing purchaser_deals</h1>

<table>
  <tr>
    <th>Purchaser</th>
    <th>Deal</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @purchaser_deals.each do |purchaser_deal| %>
  <tr>
    <td><%= purchaser_deal.purchaser %></td>
    <td><%= purchaser_deal.deal %></td>
    <td><%= link_to 'Show', purchaser_deal %></td>
    <td><%= link_to 'Edit', edit_purchaser_deal_path(purchaser_deal) %></td>
    <td><%= link_to 'Destroy', purchaser_deal, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Purchaser deal', new_purchaser_deal_path %>

deals/app/views/purchaser_deals/new.html.erb
<h1>New purchaser_deal</h1>

<%= render 'form' %>

<%= link_to 'Back', purchaser_deals_path %>

deals/app/views/purchaser_deals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Purchaser:</b>
  <%= @purchaser_deal.purchaser %>
</p>

<p>
  <b>Deal:</b>
  <%= @purchaser_deal.deal %>
</p>


<%= link_to 'Edit', edit_purchaser_deal_path(@purchaser_deal) %> |
<%= link_to 'Back', purchaser_deals_path %>