deals/config/routes.rb
Deals::Application.routes.draw do
  
  match "conversion/uploadFile", :via => 'post'
  resources :conversion

  resources :purchaser_deals

  resources :deals

  resources :merchants

  resources :purchasers

end

deals/app/models/merchant.rb
class Merchant < ActiveRecord::Base
  has_many :deals
end

deals/app/controllers/merchants_controller.rb
class MerchantsController < ApplicationController
  # GET /merchants
  # GET /merchants.json
  def index
    @merchants = Merchant.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @merchants }
    end
  end

  # GET /merchants/1
  # GET /merchants/1.json
  def show
    @merchant = Merchant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @merchant }
    end
  end

  # GET /merchants/new
  # GET /merchants/new.json
  def new
    @merchant = Merchant.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @merchant }
    end
  end

  # GET /merchants/1/edit
  def edit
    @merchant = Merchant.find(params[:id])
  end

  # POST /merchants
  # POST /merchants.json
  def create
    @merchant = Merchant.new(params[:merchant])

    respond_to do |format|
      if @merchant.save
        format.html { redirect_to @merchant, notice: 'Merchant was successfully created.' }
        format.json { render json: @merchant, status: :created, location: @merchant }
      else
        format.html { render action: "new" }
        format.json { render json: @merchant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /merchants/1
  # PUT /merchants/1.json
  def update
    @merchant = Merchant.find(params[:id])

    respond_to do |format|
      if @merchant.update_attributes(params[:merchant])
        format.html { redirect_to @merchant, notice: 'Merchant was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @merchant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /merchants/1
  # DELETE /merchants/1.json
  def destroy
    @merchant = Merchant.find(params[:id])
    @merchant.destroy

    respond_to do |format|
      format.html { redirect_to merchants_url }
      format.json { head :ok }
    end
  end
end

deals/app/helpers/merchants_helper.rb
module MerchantsHelper
end

deals/app/views/merchants/_form.html.erb
<%= form_for(@merchant) do |f| %>
  <% if @merchant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@merchant.errors.count, "error") %> prohibited this merchant from being saved:</h2>

      <ul>
      <% @merchant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

deals/app/views/merchants/edit.html.erb
<h1>Editing merchant</h1>

<%= render 'form' %>

<%= link_to 'Show', @merchant %> |
<%= link_to 'Back', merchants_path %>

deals/app/views/merchants/index.html.erb
<h1>Listing merchants</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @merchants.each do |merchant| %>
  <tr>
    <td><%= merchant.name %></td>
    <td><%= merchant.address %></td>
    <td><%= link_to 'Show', merchant %></td>
    <td><%= link_to 'Edit', edit_merchant_path(merchant) %></td>
    <td><%= link_to 'Destroy', merchant, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Merchant', new_merchant_path %>

deals/app/views/merchants/new.html.erb
<h1>New merchant</h1>

<%= render 'form' %>

<%= link_to 'Back', merchants_path %>

deals/app/views/merchants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @merchant.name %>
</p>

<p>
  <b>Address:</b>
  <%= @merchant.address %>
</p>


<%= link_to 'Edit', edit_merchant_path(@merchant) %> |
<%= link_to 'Back', merchants_path %>