deals/config/routes.rb
Deals::Application.routes.draw do
  
  match "conversion/uploadFile", :via => 'post'
  resources :conversion

  resources :purchaser_deals

  resources :deals

  resources :merchants

  resources :purchasers

end

deals/app/models/deal.rb
class Deal < ActiveRecord::Base
  belongs_to :merchant
  has_many :purchaserDeals
end

deals/app/controllers/deals_controller.rb
class DealsController < ApplicationController
  # GET /deals
  # GET /deals.json
  def index
    @deals = Deal.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @deals }
    end
  end

  # GET /deals/1
  # GET /deals/1.json
  def show
    @deal = Deal.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @deal }
    end
  end

  # GET /deals/new
  # GET /deals/new.json
  def new
    @deal = Deal.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @deal }
    end
  end

  # GET /deals/1/edit
  def edit
    @deal = Deal.find(params[:id])
  end

  # POST /deals
  # POST /deals.json
  def create
    @deal = Deal.new(params[:deal])

    respond_to do |format|
      if @deal.save
        format.html { redirect_to @deal, notice: 'Deal was successfully created.' }
        format.json { render json: @deal, status: :created, location: @deal }
      else
        format.html { render action: "new" }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /deals/1
  # PUT /deals/1.json
  def update
    @deal = Deal.find(params[:id])

    respond_to do |format|
      if @deal.update_attributes(params[:deal])
        format.html { redirect_to @deal, notice: 'Deal was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deals/1
  # DELETE /deals/1.json
  def destroy
    @deal = Deal.find(params[:id])
    @deal.destroy

    respond_to do |format|
      format.html { redirect_to deals_url }
      format.json { head :ok }
    end
  end
end

deals/app/helpers/deals_helper.rb
module DealsHelper
end

deals/app/views/deals/_form.html.erb
<%= form_for(@deal) do |f| %>
  <% if @deal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@deal.errors.count, "error") %> prohibited this deal from being saved:</h2>

      <ul>
      <% @deal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :number_purchased %><br />
    <%= f.number_field :number_purchased %>
  </div>
  <div class="field">
    <%= f.label :merchant %><br />
    <%= f.text_field :merchant %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

deals/app/views/deals/edit.html.erb
<h1>Editing deal</h1>

<%= render 'form' %>

<%= link_to 'Show', @deal %> |
<%= link_to 'Back', deals_path %>

deals/app/views/deals/index.html.erb
<h1>Listing deals</h1>

<table>
  <tr>
    <th>Description</th>
    <th>Price</th>
    <th>Number Purchased</th>
    <th>Merchant</th>
    <th>Merchant Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @deals.each do |deal| %>
  <tr>
    <td><%= deal.description %></td>
    <td><%= deal.price %></td>
    <td><%= deal.number_purchased %></td>
    <td><%= deal.merchant %></td>    
    <td><%= deal.merchant.name %></td>
    <td><%= link_to 'Show', deal %></td>
    <td><%= link_to 'Edit', edit_deal_path(deal) %></td>
    <td><%= link_to 'Destroy', deal, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Deal', new_deal_path %>

deals/app/views/deals/new.html.erb
<h1>New deal</h1>

<%= render 'form' %>

<%= link_to 'Back', deals_path %>

deals/app/views/deals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @deal.description %>
</p>

<p>
  <b>Price:</b>
  <%= @deal.price %>
</p>

<p>
  <b>number_purchased:</b>
  <%= @deal.number_purchased %>
</p>

<p>
  <b>Merchant:</b>
  <%= @deal.merchant %>
</p>


<%= link_to 'Edit', edit_deal_path(@deal) %> |
<%= link_to 'Back', deals_path %>